### ISSUE TITLE
Call-A-Bike networks data retrieval error

### ISSUE THREAD

**Issue by fpletz** [bparmentier/OpenBikeSharing#12]
All Call-A-Bike networks, for example Berlin or Munich, are not working with version 1.7.2. When selected, trying to refresh the stations lists results in a toast message saying "Error retrieving data".

**Comment by bparmentier** [comment]
Thanks for reporting the issue.

The Call-A-Bike networks were recently added to the CityBik.es API and introduced a new kind of value for the number of empty slots: *null*.

I'm working on it.

**Comment by fpletz** [comment]
Thanks for fixing this so quickly! I'll wait until the next release and get back to you then.

**Comment by fpletz** [comment]
@bparmentier Thanks again. Just tested the new release and can confirm that it works now! :+1:
