### ISSUE TITLE
Configurable Citybikes api URL

### ISSUE THREAD

**Issue by thesebas** [bparmentier/OpenBikeSharing#19]
Since https://github.com/eskerda/PyBikes looks like is stale, no pull request responses for more than month and biking season is "almost over" I can't wait any longer for merging my pull requests (added 11 Polish bike networks), maybe that's good idea to allow customize API url in app settings. I'm ready to fork and setup own API server (with new networks added) but don't want to fork and maintain this app :).

**Comment by bparmentier** [comment]
I'm not against allowing to set a custom API URL in the settings, but I would prefer to keep it hidden from the casual user to prevent him messing up with it.

Meanwhile, if we ping @eskerda, maybe he will look at your PR.

**Comment by eskerda** [comment]
Given that the CB project is free it might make sense to add this setting, even if it's hidden under 3 buttons to avoid messing up. API mirrors might pop up some day
