### ISSUE TITLE
MapQuest-OSM not working anymore

### ISSUE THREAD

**Issue by github-user-1** [bparmentier/OpenBikeSharing#33]
Hello,
the MapQuest-OSM is not working anymore:

![screenshot](https://cloud.githubusercontent.com/assets/6796538/17169049/29b79d2a-53d5-11e6-95fc-6450a830f6ca.png)

**Comment by bparmentier** [comment]
I will remove MapQuest-OSM support in the next version since they now require an API key.

I may reconsider this in the future if I find a good way on how to handle API keys in open source projects.

**Comment by frazzmark** [comment]
Can't you use the osmdroid library? I don't think it requires api keys

**Comment by bparmentier** [comment]
osmdroid is the library that gives the possibility to use map tiles from various services, including Mapnik (OSM default rendering, no API key needed) and MapQuest (API key needed).
There are some other tiles providers that we could add: https://github.com/osmdroid/osmdroid/wiki/Map-Sources#online-map-sources-out-of-the-box

**Comment by bparmentier** [comment]
Support for MapQuest-OSM was removed in b6c8550b2bd0a99b57df8e0adfa40d0c1785847b.
