### ISSUE TITLE
Swipe down to refresh

### ISSUE THREAD

**Issue by StefanBrand** [bparmentier/OpenBikeSharing#36]
This would eliminate one button from the upper bar and I think that swipe to refresh is pretty self-explaining nowadays.

**Comment by frazzmark** [comment]
That is already done, it just needs a bump in the app version.

**Comment by StefanBrand** [comment]
Any estimate, when you expect that _bump in the app version_ to be available on F-Droid? :)

**Comment by bparmentier** [comment]
Hello,

I'm really sorry for my lack of activity on this project over the last few months. I will try to produce a new release by the end of the week.
