### ISSUE TITLE
New provider in Paris

### ISSUE THREAD

**Issue by Phyks** [bparmentier/OpenBikeSharing#44]
Hi,

The velib provider in Paris changed on January, 1st. It seems OpenBikeSharing is only fetching stations from the previous provider (JCDevaux)) but not the new one. There are some remaining stations from the old provider but all stations should move to the new one in a couple of months. 

An official opendata endpoint is available from https://opendata.paris.fr/explore/dataset/velib-disponibilite-en-temps-reel/

It would be awesome to have them in OBS. Let me know if needed, I can help translate the doc if needed. But I can't do much Android coding :/

Thanks!

**Comment by bparmentier** [comment]
Hi, please see this similar issue: https://github.com/bparmentier/OpenBikeSharing/issues/43

OpenBikeSharing is using PyBikes to retrieve its data. An issue has already been opened there: https://github.com/eskerda/pybikes/issues/299.

**Comment by Phyks** [comment]
Oh, really sorry I missed it. :/ thanks!

**Comment by Phyks** [comment]
@bparmentier Small update on this : Velib provider in PyBike has been updated, and it seems to be working in OBS now! :)

However, it returns all available stations, even the ones not already open. There is a discussion going on about how to standardize ebikes and WIP status management, you might be interested in it: https://github.com/eskerda/pybikes/pull/300#issuecomment-357963626.
